name: energy_management
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_calendar: 
  

  intl: ^0.18.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  build_runner: ^2.3.3




flutter:
  generate : true
  uses-material-design: true
assets:
  fonts:
    - family: montserrat
      fonts:
        - asset: fonts/cedarvillecursive_regular.ttf
